create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  alias text,
  created_at timestamptz default now()
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  period text not null,
  module text not null check (module in ('bank', 'z', 'receipt')),
  original_name text not null,
  stored_path text not null,
  status text not null,
  warnings text default '[]',
  created_at timestamptz default now()
);

create table if not exists public.bank_transactions (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.documents(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  period text not null,
  bank_name text,
  account_no_or_iban text,
  date text,
  description text,
  debit text,
  credit text,
  balance text,
  currency text,
  counterparty_guess text,
  transaction_hash text,
  duplicate_flag boolean default false,
  suggested_account_code text,
  confidence double precision,
  needs_review boolean default false,
  source_row integer,
  created_at timestamptz default now()
);

create table if not exists public.z_reports (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.documents(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  period text not null,
  source_file text,
  report_date text,
  device_brand text,
  device_serial text,
  z_no text,
  gross_total text,
  vat_lines text,
  payment_breakdown text,
  confidence double precision,
  needs_review boolean default false,
  raw_text text,
  created_at timestamptz default now()
);

create table if not exists public.receipts (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.documents(id) on delete cascade,
  client_id bigint not null references public.clients(id) on delete cascade,
  period text not null,
  source_file text,
  receipt_date text,
  merchant_name text,
  vkn_tckn text,
  document_no text,
  gross_total text,
  vat_total text,
  payment_method text,
  bookkeeping_status text,
  confidence double precision,
  needs_review boolean default false,
  raw_text text,
  created_at timestamptz default now()
);

create table if not exists public.account_code_rules (
  id bigint generated by default as identity primary key,
  client_id bigint references public.clients(id) on delete cascade,
  pattern text not null,
  account_code text not null,
  source text default 'manual',
  created_at timestamptz default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  item_type text not null check (item_type in ('bank', 'z', 'receipt')),
  item_id bigint not null,
  rating text not null check (rating in ('dogru', 'yanlis', 'eksik', 'gereksiz')),
  note text,
  created_at timestamptz default now()
);

create index if not exists documents_client_period_idx on public.documents (client_id, period);
create index if not exists bank_transactions_client_period_idx on public.bank_transactions (client_id, period);
create index if not exists bank_transactions_review_idx on public.bank_transactions (needs_review, client_id, period);
create index if not exists z_reports_client_period_idx on public.z_reports (client_id, period);
create index if not exists z_reports_review_idx on public.z_reports (needs_review, client_id, period);
create index if not exists receipts_client_period_idx on public.receipts (client_id, period);
create index if not exists receipts_review_idx on public.receipts (needs_review, client_id, period);
create index if not exists account_code_rules_client_idx on public.account_code_rules (client_id);
create index if not exists feedback_item_idx on public.feedback (item_type, item_id);

alter table public.clients enable row level security;
alter table public.documents enable row level security;
alter table public.bank_transactions enable row level security;
alter table public.z_reports enable row level security;
alter table public.receipts enable row level security;
alter table public.account_code_rules enable row level security;
alter table public.feedback enable row level security;

insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do nothing;

